export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL;";
export const USER_LOADED = "USER_LOADED";
export const ADMIN_LOADED = "ADMIN_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";

export const GET_USERS = "GET_USERS";
export const GET_USER_BY_ID = "GET_USER_BY_ID";
export const CLEAR_USER = "CLEAR_USER";

export const LOAD_CHAPTERS = "LOAD_CHAPTERS";
export const SELECT_CHAPTER = "SELECT_CHAPTER";
export const REMOVE_CHAPTER = "REMOVE_CHAPTER";
export const FILTER_CHAPTERS = "FILTER_CHAPTERS";
export const CLEAR_FILTERED_CHAPTERS = "CLEAR_FILTERED_CHAPTERS";

export const GET_NEWS = "GET_NEWS";
export const GET_NEWS_BY_TITLE = "GET_NEWS_BY_TITLE";

export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const OPEN_DRAWER = "OPEN_DRAWER";
export const SELECT_LIST_ITEM = "SELECT_LIST_ITEM";
export const OPEN_EDITOR_MODAL = "OPEN_EDITOR_MODAL";
export const CLOSE_EDITOR_MODAL = "CLOSE_EDITOR_MODAL";
